### ISSUE TITLE
Request to fix License name in package.json 

### ISSUE THREAD

**Issue by k7ragav** [fabio-looker/node-lookml-parser#21]
Hi,

I'd like to propose to change the license from "Unlicensed" to "MIT" in the package.json file

Context:
I work for a financial institution where we adhere to stringent software usage policies. As part of our protocol, we rely exclusively on pre-vetted npm packages to ensure stability and security.

Even though there is a MIT license for this project, the "Unlicensed" mention here: https://www.npmjs.com/package/lookml-parser is being a blocker for us. Our process scans through the license name in the npm package and since it is "Unlicensed", the package is not being greenlit. Therefore, changing the name in package.json could help us.

Given the above concerns, I kindly request the consideration for changing the license name in the npm package. This change would greatly assist organizations like ours in maintaining a stable and secure software environment.

Thank you for your understanding and consideration.

Best regards,

Keshava Ragavendra

**Comment by fabio-looker** [comment]
Hi @k7ragav 

Thanks for this PR and the one in the look-at-me-sideways (LAMS) repo too. I guess an NPM publish is required as well for your automation to pick these changes up too?

And for LAMS I imagine you need the package.json/dependency updated as well. I just got back from OOO and am catching up on emails, but I should be able to get these both updated in the next day or two

**Comment by k7ragav** [comment]
Hi @fabio-looker 

Thanks for the response. Yes, I think it would require an NPM publish too. Is that something that can be done by you?

And yes, I think for LAMS that needs to be done too. I can add that in the same PR there too. 

Thanks!

**Comment by fabio-looker** [comment]
Hi, I fixed this in https://github.com/fabio-looker/node-lookml-parser/commit/ef7db98885501d6d9edfe573a9c57d83ba7ea82f and also renamed the LICENSE.txt file to LICENSE, and published these to NPM as 6.8.1. I'll work on the linter update next.
