### ISSUE TITLE
Not all Include paths parsed and followed 

### ISSUE THREAD

**Issue by langusto-bytecode** [fabio-looker/node-lookml-parser#24]
These include statements `include: "../explores/*.explore"` `include: "../views/*.view"` are valid in Looker for the model and explore files, respectively, in a project with the following folder structure. lookml-parser does not follow these paths and pull in the appropriate files. 

- marketing
  - explores
    - base.explore.lkml
  - model
    - marketing.model
  - views
    - view_1.view
    - view_2.view

**Comment by fabio-looker** [comment]
Hi @langusto-bytecode  - Can you confirm how you are invoking the parser? Includes are only followed among the files that were input to the parser, and the default input argument does not include ".explore.lkml" files

**Comment by fabio-looker** [comment]
Whoops, I remembered incorrectly, the default input does include ".explore" files: https://github.com/fabio-looker/node-lookml-parser/blob/master/lib/parse-files/index.js#L10

Still, could you confirm how you are invoking the parser? I'll see if any other possible cause is apparent

**Comment by fabio-looker** [comment]
Seems like my highly ad-hoc recreation of the file matching logic did not include ".." paths: https://github.com/fabio-looker/node-lookml-parser/blob/master/lib/parse-files/index.js#L167

Should be a pretty quick fix, and I was already hoping to make some fixes to the parser this week...

**Comment by langusto-bytecode** [comment]
Awesome to hear it should be a quick fix! It took me a while to figure out the root cause of why LAMS wasn't finding any matches

**Comment by fabio-looker** [comment]
Should be working in v6.8.2, lemme know if you still have any issues :)

https://github.com/fabio-looker/node-lookml-parser/blob/a1e2bd21397ff33dbfafa6166459100ba9ad5d64/lib/transformations/assemble-models.js#L110
