### ISSUE TITLE
Are Dashboards supported?

### ISSUE THREAD

**Issue by michaelsmithhx** [fabio-looker/node-lookml-parser#3]
Hi Fabio,
I am very new to Looker, but am keen to see if your tool could be used to extract dependencies to our datasource. It seems to work very nicely for Views and Explores, however when I run a test case against one of our Dashboard Look MLs it is unable to parse. Are there any plans to support Dashboards in the parser?
Kind Regards,
Mike

**Comment by fabiocbinbutter** [comment]
Hi! "Lookml" dashboards are actually YAML. While this project was initially a simple grammar purely for lookml syntax, lately it has grown to encompass the interpretation of the whole LookMl project, so I might consider adding dashboard support via an optional peer dependency. In the meantime though, you should be able to use a separate YAML parser for dashboards

**Comment by michaelsmithhx** [comment]
OK, thanks Fabio!

**Comment by langusto-bytecode** [comment]
Any potential for revisiting this enhancement?

**Comment by fabio-looker** [comment]
Yes, I've been thinking about implementing support for it, IF the user
installs a YAML module as a peer dependency, so as to keep the package size
small for users who do not need the functionality. Still need to validate
whether this approach will work.

**Comment by fabio-looker** [comment]
This is implemented (un-documented) in 6.9.0. Wanted to publish it to NPM first to validate exactly how users can install the js-yaml peer dependency. Once that's tested, I'll update LAMS to use this functionality as well.

**Comment by fabio-looker** [comment]
lookml-parser@6.9.1 and look-at-me-sideways@3.2.0 now both support LookML Dashboards. Separate install of optional dependency `js-yaml` is required for this functionality.
