### ISSUE TITLE
not extracting info from explore file

### ISSUE THREAD

**Issue by weightwatchers-carlanderson** [fabio-looker/node-lookml-parser#7]
@fabio-looker The behavior seems to have changed with this file in 5.0.0 from 4.x and is not capturing any info from the file. 

```
(env) nycCANDERSONmbp:wwtech-lookml-tools carl.anderson$ more test/grapher_lkml/some_explore.exlore.lkml

include: "*.view.lkml"
explore: some_explore {
    from: some_view
    join: some_other_view {
        from: some_other_view
    }
}
(env) nycCANDERSONmbp:wwtech-lookml-tools carl.anderson$ lookml-parser --input=test/grapher_lkml/some_explore.exlore.lkml --whitespace=2 > parsed_lookml.json
(env) nycCANDERSONmbp:wwtech-lookml-tools carl.anderson$ more parsed_lookml.json 
{
  "file": {
    "model": {},
    "view": {},
    "explore": {}
  },
  "model": {}
}
(env) nycCANDERSONmbp:wwtech-lookml-tools carl.anderson$ ls test/grapher_lkml/
orphan_view.view.lkml      some_explore.exlore.lkml   some_model.model.lkml      some_other_view.view.lkml  some_view.view.lkml         
```

**Comment by fabio-looker** [comment]
Hi Carl, this one looks like it might just be a typo in your command line argument? 
`--input=test/grapher_lkml/some_explore.exlore.lkml`

(note the `exlore` missing a p )

Closing this out for now, but let me know if you're still seeing any issue and I'll reopen

**Comment by weightwatchers-carlanderson** [comment]
@fabio-looker Thanks for looking into it. The command was correct--I was pointing to the correct file, which existed---it was just that the explore file was named incorrectly and the parser silently ignored it. It could be nice for the tool to flag that it only recognizes `*.model.lkml`, `*.view.lkml` and `*.explore.lkml`. Does Looker really impose that naming convention?

**Comment by fabio-looker** [comment]
I think it will warn about different filenames, but may parse them anyway. I'll look into making the "by-type" output less strict or less silent, but until then, the "by name" or "array" outputs will not filter any filetypes!
